version: '3.8'

volumes:
  vault_data: {}

services:
  vault:
    image: hashicorp/vault:latest
    volumes:
      - vault_data:/vault/file
      - ./config/:/vault/config
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl